version: "3.8"
services:
  api:
    build: .
    container_name: 'api'
    image: 'api:1'
    networks:
      - backend
    ports:
      - '${API_PORT}:80'
    env_file:
      - .env
    volumes:
      - ./src:/service/src
    restart: unless-stopped

networks:
  backend: