version: "3.8"
services:
  api:
    build: .
    container_name: api
    image: api:1
    env_file: .env.example
    networks:
      - backend
    ports:
      - '${API_PORT}:80'
    volumes:
      - ./src:/service/src
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    env_file: .env.example
    ports:
      - '27017:27017'
    volumes:
      - db_data6:/data/db
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  db_data6: